data:
  image: busybox
  volumes:
    - /var/lib/mysql
wordpress:
  image: visiblevc/wordpress
  links:
    - mysql
  ports:
    - 8080:80
    - 443:443
  volumes:
    - ./data:/data
    - ./wp-content/uploads:/app/wp-content/uploads
    - ./wp-content/plugins:/app/wp-content/plugins
    - ./wp-content/themes/my-theme:/app/wp-content/themes/my-theme
  environment:
    DB_NAME: wordpress
mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: root
